### ISSUE TITLE
切换fragment的时候，会出现重叠。

### ISSUE THREAD

**Issue by ericacx** [xiaohaibin/XMarqueeView#1]

**Comment by xiaohaibin** [comment]
#### 重影问题可参考以下解决方案

    @Override
    public void onStart() {
        super.onStart(); 
        marqueeView.startFlipping();
    }

    @Override
    public void onStop() {
        super.onStop();
        marqueeView.stopFlipping();
    }

**Comment by shortybin** [comment]
根据 fragment 的生命周期去调用 marqueeView.startFlipping() 和 marqueeView.stopFlipping()
show、hide 和 release 生命周期不同
只能根据实际情况调用方法
