### ISSUE TITLE
解决部分设备上 ViewFlipper 加载较多 View 时卡顿问题

### ISSUE THREAD

**Issue by ZDZN** [xiaohaibin/XMarqueeView#2]
我看过大部分 github 上的同类垂直轮播（继承 ViewFlipper 自定义 View）的开源库，但基本找不到能解决这个问题的方案，针对此问题，在此提出并介绍一下解决办法。
解决办法主要参考 [StackOverflow](https://stackoverflow.com/questions/7338351/how-to-improve-the-performance-of-viewflipper-viewanimator) 上的一个答案。
方法就是在 ViewFlipper 定义的 xml 中加入 `android:measureAllChildren="false"` 这个属性值，或者你可以在继承 ViewFlipper 的自定义 View 的初始化代码中加入 `setMeasureAllChildren(false);` 即可。

另外如果对轮播动画效果没什么要求的，完全可以使用 AdapterViewFlipper 来实现，该控件对 View 的缓存应该比 github 上能找到的大部分同类的垂直轮播（继承 ViewFlipper 自定义 View）的开源库做得好，毕竟有父类是 AdapterView，跟 ListView 父类一样，用 AdapterViewFlipper 应该能减少更多卡顿问题。

**Comment by xiaohaibin** [comment]
好的，感谢，我试下

**Comment by xiaohaibin** [comment]
已添加上
